SuperchargedTradingEngine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from users import views as users_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'),name = 'logout'),
    path('welcome/', users_views.welcome,name='welcome'),
    path('register/', users_views.register,name='register'),
]

if(settings.DEBUG):
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

orders/api/urls.py
from django.urls import path

from rest_framework.authtoken import views

from .views import OrderAPIView, OrderDetailAPIView, TradeAPIView, TradeDetailAPIView, signup

urlpatterns = [
    path('signup/', signup),
    path('token/', views.obtain_auth_token),
    path('orders/', OrderAPIView.as_view()),
    path('orders/<int:pk>/', OrderDetailAPIView.as_view()),
    path('trades/', TradeAPIView.as_view()),
    path('trades/<int:pk>/', TradeDetailAPIView.as_view()),
]

orders/urls.py
from django.urls import path, include

from .views import OrderCreateView, OrderListView, OrderUpdateView, OrderDeleteView, TradeListView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name = 'users/login.html'),name = 'login'),
    path('api/', include('orders.api.urls')),
    path('orders/', OrderListView.as_view(), name = 'orders-list'),
    path('orders/new/', OrderCreateView.as_view(), name = 'order-create'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name = 'order-update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name = 'order-delete'),
    path('trades/', TradeListView.as_view(), name = 'trades-list'),
]

orders/models.py
from django.utils import timezone
from django.db import models
from django.core.validators import MinValueValidator, MinLengthValidator
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.urls import reverse

TYPE_CHOICES = (('M', 'Market'), ('L', 'Limit'),)
SIDE_CHOICES = (('B', 'Buy'), ('S', 'Sell'),)

class Order(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    side = models.CharField(max_length=1, choices=SIDE_CHOICES)
    price = models.FloatField(default=0.0, validators=[MinValueValidator(0.0)])
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    stock_code = models.CharField(max_length=6, validators=[MinLengthValidator(6)])
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.user}-{self.timestamp}'

    def get_absolute_url(self):
        return reverse('orders-list')

class Trade(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='buyer_user')
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='seller_user')
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    timestamp = models.DateTimeField(default=timezone.now)
    price = models.FloatField(default=0.0, validators=[MinValueValidator(0.0)])
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    stock_code = models.CharField(max_length=6, validators=[MinLengthValidator(6)])

    def save(self, *args, **kwargs):
        if self.buyer != self.seller:
            super(Trade, self).save(*args, **kwargs)
        else:
            raise ValidationError('Buyer and Seller cannot be same')

    def __str__(self):
        return f'Buyer: {self.buyer}, Seller: {self.seller}'

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
	email=forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

orders/api/views.py
import json

from django.contrib.auth.models import User

from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from rest_framework import generics, mixins
from rest_framework.decorators import api_view, authentication_classes, permission_classes

from .permissions import IsOwnerOrReadOnly
from .serializers import OrderSerializer, TradeSerializer
from ..models import Order, Trade

class OrderDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [IsOwnerOrReadOnly]
    queryset = Order.objects.all()
    serializer_class = OrderSerializer


class OrderAPIView(mixins.CreateModelMixin, generics.ListAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def perform_create(self, serializer):
        serializer.save(user = self.request.user)

class TradeDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [IsOwnerOrReadOnly]
    queryset = Trade.objects.all()
    serializer_class = TradeSerializer

class TradeAPIView(generics.ListAPIView):
    queryset = Trade.objects.all()
    serializer_class = TradeSerializer

@api_view(["POST"])
@authentication_classes([])
@permission_classes([])
def signup(request):
    # print(json.loads(request.body)['username'])
    # print(json.loads(request.body)['password'])
    body = json.loads(request.body)
    email = body['email']
    username = body['username']
    password = body['password']
    user = User.objects.create_user(email=email, username=username, password=password)
    token = Token.objects.create(user=user)
    # print(token.key)
    return Response('Registration successful')

orders/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from collections import defaultdict

from .models import Order, Trade

rs = set([1,2,3])

stock_thread_dict = dict()

stock_list_dict = dict()

class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    template_name = 'orders/order_create.html'
    fields = ['type', 'side', 'price', 'quantity', 'stock_code']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'orders/order_list.html'
    ordering =['-timestamp']
    context_object_name='orders'

class OrderUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Order
    fields = ['type', 'side', 'price', 'quantity', 'stock_code']
    template_name = 'orders/order_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        order = self.get_object()
        if order.user == self.request.user:
            return True
        else:
            return False

class OrderDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Order
    success_url ='/orders'

    def test_func(self):
        order = self.get_object()
        if order.user == self.request.user:
            return True
        else:
            return False

class TradeListView(LoginRequiredMixin, ListView):
    model = Trade
    template_name = 'orders/trade_list.html'
    ordering =['-timestamp']
    context_object_name='trades'

users/views.py
from django.shortcuts import render,redirect
from users.forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth.models import User

# Create your views here.
def register(request):
	if request.method=='POST':
		form=UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Your account has been created! You are now able to log in')
			return redirect('login')
	else:
		form = UserRegisterForm()
	return render(request, "users/register.html", {'form': form})

def welcome(request):
    return render(request, "users/welcome.html")

orders/templates/orders/order_confirm_delete.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Confirm Delete Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <style>
      html, body {
        overflow-x: hidden;
        background-image: url("https://image.freepik.com/free-vector/business-candle-stick-graph-chart-stock-market-investment-trading-blue-background_62391-73.jpg");
        background-size: cover;
      }
    </style>
</head>
<body>


<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <p class="text-light"><h3 style="color: white;">Supercharged Trading Engine</h3></p>
    </li>
  </ul>
</nav>
<br>
<br>
	<div class = "container" style="margin-left:200px ;width: 1000px;">
		<form method = "POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4" style="color: white;">Delete Order</legend>
				<h2 style="justify-content: center;color: white;">Are you sure you want to delete the order ?</h2>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-danger" type="submit">Yes, Delete</button>
				<a class="btn btn-danger" href = "{% url 'orders-list' %}" type="submit" style="margin-left: 20px;">Cancel</a>
			</div>
		</form>
	</div>
{% endblock content %}

orders/templates/orders/order_create.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Order Create</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <style>
      html, body {
      min-height: 100%;
      background-image: url("https://image.freepik.com/free-vector/business-candle-stick-graph-chart-stock-market-investment-trading-blue-background_62391-73.jpg");
      background-size: cover;
      }
      .nav-item a:hover{
        border-bottom: 3px solid rgb(49, 17, 192);
      }
      body, div, form, input, label { 
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 13px;
      color: #666;
      line-height: 22px;
      }
      legend { 
      color: #fff;
      background-color: #095484;
      padding: 3px 5px;
      font-size: 20px;
      }
      h1 {
      position: absolute;
      margin: 0;
      font-size: 36px;
      color: #fff;
      z-index: 2;
      }
      .testbox {
      display: flex;
      justify-content: center;
      align-items: center;
      height: inherit;
      padding: 20px;
      }
      form {
      width: 100%;
      padding: 20px;
      border-radius: 6px;
      background: #fff;
      box-shadow: 0 0 20px 0  #095484; 
      }
      .banner {
      position: relative;
      height: 320px;
      background-image: url("https://png.pngtree.com/thumb_back/fw800/background/20191105/pngtree-blue-purple-financial-stock-market-background-image_321086.jpg");  
      background-size: cover;
      display: flex;
      justify-content: center;
      align-items: center;
      text-align: center;
      }
      .banner::after {
      content: "";
      background-color: rgba(0, 0, 0, 0.6); 
      position: absolute;
      width: 100%;
      height: 100%;
      }
      input {
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 3px;
      }
      input {
      width: calc(100% - 10px);
      padding: 5px;
      }
      select {
      width: 100%;
      padding: 7px 0;
      background: transparent;
      }
      input[type="date"] {
      padding: 4px 5px;
      }
      .item:hover p, .item:hover i, .question:hover p, .question label:hover, input:hover::placeholder {
      color:#095484;
      }
      .item input:hover {
      border: 1px solid transparent;
      box-shadow: 0 0 6px 0 #095484;
      color:#095484;
      }
      .item {
      position: relative;
      margin: 10px 0;
      }
      .item span {
      color: red;
      }
      input[type="date"]::-webkit-inner-spin-button {
      display: none;
      }
      .item i, input[type="date"]::-webkit-calendar-picker-indicator {
      position: absolute;
      font-size: 20px;
      color: #095484;
      }
      .item i {
      right: 2%;
      top: 30px;
      z-index: 1;
      }
      [type="date"]::-webkit-calendar-picker-indicator {
      right: 1%;
      z-index: 2;
      opacity: 0;
      cursor: pointer;
      }
      .question span {
      margin-left: 30px;
      }
      .btn-block {
      margin-top: 10px;
      text-align: center;
      }
      button {
      width: 150px;
      padding: 10px;
      border: none;
      border-radius: 5px; 
      background: #095484;
      font-size: 16px;
      color: #fff;
      cursor: pointer;
      }
      button:hover {
      background: #4286f4;
      }
      @media (min-width: 568px) {
      .name-item, .city-item {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      }
      .name-item input, .city-item input,.name-item div {
      width: calc(50% - 20px);
      }
      .name-item div input {
      width:97%;}
      .name-item div label {
      display:block;
      padding-bottom:5px;
      }
      }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <p class="text-light"><h3 style="color: white;">Supercharged Trading Engine</h3></p>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a class="text-ligt nav-link" href="{%url 'order-create' %}" style="color: white;font-size: 20px;padding-right: 8px;">Create Order</a>
    </li>
    <li class="nav-item">
      <a class="text-ligt nav-link" href="{%url 'trades-list' %}" style="color: white;font-size: 20px;padding-right: 8px;">All Trades</a>
    </li>
    <li class="nav-item">
      <a class="text-ligt nav-link" href="{%url 'orders-list' %}" style="color: white;font-size: 20px;padding-right: 8px;">All Orders</a>
    </li>
    <li class="nav-item"> 
      <a class="text-ligt nav-link" href="{% url 'logout' %} " style="color: white; font-size: 20px;padding-right: 20px;">Logout</a>
    </li>
    <li class="nav-item">
      <a class="text-ligt nav-link" href="#" style="color: white;font-size: 20px;padding-right: 5px;">{{user.username}}</a>
    </li>
  </ul>
</nav>
<br>
    <div class="testbox">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="banner">
        <h1>Create Order Form</h1>
      </div>
      <p>Please fill out with the information that is requested below and submit the form. Thank you!</p>
      <hr/>
      <fieldset>
        <legend>Order Information</legend>
        <div class="item">
            {{ form|crispy }}
        </div>
      </fieldset>
      <div class="btn-block">
        <button type="submit" href="{% url 'orders-list' %}">Create Order</button>
        </div>
    </form>
    </div>
  </body>
</html>

orders/templates/orders/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Order List</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <style>
      html, body {
        overflow-x: hidden;
        background-image: url("https://image.freepik.com/free-vector/business-candle-stick-graph-chart-stock-market-investment-trading-blue-background_62391-73.jpg");
        background-size: cover;
      }
      .nav-item a:hover{
        border-bottom: 3px solid rgb(49, 17, 192);
      }
  </style>
</head>
<body>


  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <p class="text-light"><h3 style="color: white;">Supercharged Trading Engine</h3></p>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="text-ligt nav-link" href="{%url 'order-create' %}" style="color: white;font-size: 20px;padding-right: 8px;">Create Order</a>
      </li>
      <li class="nav-item">
        <a class="text-ligt nav-link" href="{%url 'trades-list' %}" style="color: white;font-size: 20px;padding-right: 8px;">All Trades</a>
      </li>
      <li class="nav-item">
        <a class="text-ligt nav-link" href="{%url 'orders-list' %}" style="color: white;font-size: 20px;padding-right: 8px;">All Orders</a>
      </li>
      <li class="nav-item"> 
        <a class="text-ligt nav-link" href="{% url 'logout' %} " style="color: white; font-size: 20px;padding-right: 20px;">Logout</a>
      </li>
      <li class="nav-item">
        <a class="text-ligt nav-link" href="#" style="color: white;font-size: 20px;padding-right: 5px;">{{user.username}}</a>
      </li>
    </ul>
  </nav>
<br>
<div class="container">    
  <table class="table table-dark table-hover shadow-lg">
    <thead>
      <tr>
      <th class="text-center font-weight-bolder  text-uppercase " style="color: burlywood;">Type</th>
        <th class="text-center font-weight-bolder text-uppercase" style="color: burlywood;">Side</th>
        <th class="text-center font-weight-bolder text-uppercase" style="color: burlywood;">Price</th>
        <th class="text-center font-weight-bolder text-uppercase" style="color: burlywood;">Quantity</th>
        <th class="text-center font-weight-bolder text-uppercase" style="color: burlywood;">Stock Code</th>
        <th class="text-center font-weight-bolder text-uppercase" style="color: burlywood;">Timestamp</th>
        <th class="text-center font-weight-bolder text-uppercase"></th>
        <th class="text-center font-weight-bolder text-uppercase"></th>
      </tr>
    </thead>
    <tbody>
        {%if orders%}
        {% for order in orders%}
        <tr>
          <td class="text-center">{{order.get_type_display}}</td>
          <td class="text-center">{{order.get_side_display}}</td>
        <td class="text-center">{{order.price}}</td>
        <td class="text-center">{{order.quantity}}</td>
        <td class="text-center">{{order.stock_code}}</td>
        <td class="text-center">{{order.timestamp}}</td>
        {% if order.user.username == user.username %}
          <td><a href="{% url 'order-delete' order.pk %}"><button class="btn btn-danger">Delete</button></a></td>
          <td><a href="{% url 'order-update' order.pk%}"><button class="btn btn-primary">Update</button></a></td>
        {% endif %}
      </tr>
        {% endfor %}
        {% endif %}
    </tbody>
  </table>
</div>
</body>
</html

orders/templates/orders/trade_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Trade List</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <style>
      html, body {
        overflow-x: hidden;
        background-image: url("https://image.freepik.com/free-vector/business-candle-stick-graph-chart-stock-market-investment-trading-blue-background_62391-73.jpg");
        background-size: cover;
      }
      .nav-item a:hover{
        border-bottom: 3px solid rgb(49, 17, 192);
      }
  </style>
</head>
<body>


  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <p class="text-light"><h3 style="color: white;">Supercharged Trading Engine</h3></p>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="text-ligt nav-link" href="{%url 'order-create' %}" style="color: white;font-size: 20px;padding-right: 8px;">Create Order</a>
      </li>
      <li class="nav-item">
        <a class="text-ligt nav-link" href="{%url 'trades-list' %}" style="color: white;font-size: 20px;padding-right: 8px;">All Trades</a>
      </li>
      <li class="nav-item">
        <a class="text-ligt nav-link" href="{%url 'orders-list' %}" style="color: white;font-size: 20px;padding-right: 8px;">All Orders</a>
      </li>
      <li class="nav-item"> 
        <a class="text-ligt nav-link" href="{% url 'logout' %} " style="color: white; font-size: 20px;padding-right: 20px;">Logout</a>
      </li>
      <li class="nav-item">
        <a class="text-ligt nav-link" href="#" style="color: white;font-size: 20px;padding-right: 5px;">{{user.username}}</a>
      </li>
    </ul>
  </nav>
<br>
<div class="container">    
  <table class="table table-dark table-hover shadow-lg">
    <thead>
      <tr>
        <th class="text-center font-weight-bolder  text-uppercase" style="color: burlywood;">Buyer</th>
        <th class="text-center font-weight-bolder  text-uppercase" style="color: burlywood;">Seller</th>
      <th class="text-center font-weight-bolder  text-uppercase" style="color: burlywood;">Type</th>
        <th class="text-center font-weight-bolder text-uppercase" style="color: burlywood;">Price</th>
        <th class="text-center font-weight-bolder text-uppercase" style="color: burlywood;">Quantity</th>
        <th class="text-center font-weight-bolder text-uppercase" style="color: burlywood;">Stock Code</th>
        <th class="text-center font-weight-bolder text-uppercase" style="color:burlywood;">Timestamp</th>
      </tr>
    </thead>
    <tbody>
        {%if trades%}
        {% for trade in trades%}
        <tr>
            <td class="text-center">{{trade.buyer}}</td>
            <td class="text-center">{{trade.seller}}</td>  
          <td class="text-center">{{trade.get_type_display}}</td>
        <td class="text-center">{{trade.price}}</td>
        <td class="text-center">{{trade.quantity}}</td>
        <td class="text-center">{{trade.stock_code}}</td>
        <td class="text-center">{{trade.timestamp}}</td>
      </tr>
        {% endfor %}
        {% endif %}
    </tbody>
  </table>
</div>
</body>
</html